[buildPlans.ComfyCode]
family = "Comfy Code"
spacing = "fixed"
serifs = "sans"
noCvSs = true
exportGlyphNames = true
noLigation = true

[buildPlans.ComfyCode.namingOverride]
manufacturer = "zzhaolei"
description = "Comfy Code is a custom build of Iosevka, a monospace font family for programming."
urlVendor = "https://github.com/zzhaolei/comfy-code"

[buildPlans.ComfyCode.variants.design]
two = "straight-neck-serifless"
five = "oblique-flat-serifless"
eight = "two-circles"
capital-d = "more-rounded-serifless"
capital-g = "toothless-rounded-serifless-hooked"
f = "flat-hook-serifless-crossbar-at-x-height"
i = "serifed-flat-tailed"
j = "flat-hook-serifed"
l = "serifed-flat-tailed"
r = "hookless-serifless"
t = "flat-hook-short-neck2"
w = "straight-flat-top-serifless"
asterisk = "penta-mid"
paren = "large-contour"
guillemet = "straight"
number-sign = "slanted"
ampersand = "upper-open"
percent = "rings-continuous-slash"
lig-ltgteq = "slanted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"

[buildPlans.ComfyCode.variants.italic]
a = "double-storey-serifless"
d = "toothed-serifless"
e = "flat-crossbar"
f = "flat-hook-tailed-crossbar-at-x-height"
u = "toothed-serifless"
y = "straight-serifless"

[buildPlans.ComfyCode.widths.Condensed]
shape = 500
menu = 3
css = "condensed"

[buildPlans.ComfyCode.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.ComfyCode.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.ComfyCode.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
